### ISSUE TITLE
Can't log in into osu!: downloader: Login: could not log in (was not redirected to index)

### ISSUE THREAD

**Issue by ghost** [osuripple/cheesegull#13]
Could this be due to osu.ppy.sh being the new osu page, or have I set something up wrongly?

**Comment by ghost** [comment]
I was able to get it working when changing `	loginResp, err := c.PostForm("https://osu.ppy.sh/forum/ucp.php?mode=login", vals)` in downloader/downloader.go to `	loginResp, err := c.PostForm("https://old.ppy.sh/forum/ucp.php?mode=login", vals)`

**Comment by thehowl** [comment]
Yeah, I had made a temp patch on prod server a few days ago to hotfix it and forgot to do the proper patch. Might do today if I have the time

**Comment by ghost** [comment]
Alright, I probably should've made a pull request. Oh wel
