### ISSUE TITLE
Error when request from "api/search"

### ISSUE THREAD

**Issue by Helloyunho** [osuripple/cheesegull#16]
If I search for something to cheesegull API(ex: freedom), This error has occurred.
```
2018/06/17 22:55:17 Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''freedom') AND ranked_status IN (1,2)  ORDER BY WEIGHT() DESC, id DESC  LIMIT 0' at line 1
```

Am I doing something wrong? or just cheesegull's error?

**Comment by MaxKruse** [comment]
Well, do you have the correct database structure + data? whats the full Query? try sending it manually and see what happens

**Comment by Helloyunho** [comment]
@MaxKruse I don't know what is the Query but database is fine

**Comment by MaxKruse** [comment]
log the query itself and check it manually then

**Comment by Helloyunho** [comment]
I just add `fmt.Println(setsQuery)` on 'set_search.go' file but nothing shows up

**Comment by thehowl** [comment]
You'll need to use Sphinx to make search work. MySQL/MariaDB won't suffice because it lacks the fullsearch capabilities we need. There is a sample config in the README

**Comment by Helloyunho** [comment]
Now running with Sphinx but still get the same error

**Comment by thehowl** [comment]
It means you haven't changed your Search DSN to be that of sphinx, probably. Taking guesses here.

**Comment by Helloyunho** [comment]
Thanks! It worked!
